config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
	  sign_up: ''
	}
  resources :works
  resources :media_objects
  resources :resource_objects
  root to: "works#index"

end

app/models/work.rb
class Work < ActiveRecord::Base
	acts_as_taggable
	acts_as_taggable_on :creators, :locations, :languages, 
		:periods, :mediums

	geocoded_by :place
	after_validation :geocode

	has_many :media_objects
	has_many :resource_objects

	validates :title, presence: true, length: { maximum: 40 }
	validates :min_year, presence: true, length: { maximum: 5}
	validates :place, presence: true

	default_scope -> { order('min_year ASC') }

	def featured_image
		return self.media_objects.where(featured: true).first
	end

	def self.search(query)
	  where("lower(title) LIKE ?", "%#{query.downcase}%") 
	end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @title = "The Canon - Page One"
    @works = Work.all

    if params[:tags] && !params[:tags].empty?
      @tags = params[:tags].split(', ');
      @tags.each do |t|
        if Work.search(t).count > 0
          @tags.delete_at(@tags.find_index(t))
          @works = Work.search(t)
          @query = t
        end   
      end
      if !@tags.empty?
        @works = @works.tagged_with(@tags)
      end
      if @query 
        @tags << @query
      end
      @tags = @tags.join(', ')
    end

    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])
    @title = "#{@work.title} - Page One"
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to edit_work_path(@work), notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :min_year, :max_year, :circa, :place, :latitude, :is_title,
        :longitude, :creator_list, :location_list, :language_list, :period_list, :medium_list, :why)
    end

    def signed_in_user
      unless signed_in?
        redirect_to new_user_session_path, notice: "Please sign in."
      end
    end

    def signed_in?
      !current_user.nil?
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :is_title %>
    <%= f.check_box :is_title, class: "checkbox"  %>
  </div>
  <div class="field">
    <%= f.label :min_year %><br>
    <%= f.number_field :min_year %>
  </div>
  <div class="field">
    <%= f.label :max_year %><br>
    <%= f.text_field :max_year %>
  </div>
  <div class="field">
    <%= f.label :circa %>
    <%= f.check_box :circa, class: "checkbox"  %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place, id: "search-new" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit class: "button button-blue" %>
    <%= link_to 'Cancel', works_path %>
  </div>
  <br />
<% end %>

app/views/works/edit.html.erb
<%= form_for(@work) do |f| %>

  <div class="container site-inner show edit">
  	<% if @work.errors.any? %>
		  <div id="error_explanation">
	      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

	      <ul>
	      <% @work.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

		<div class="breadcrumb-container">
	    <p><%= link_to 'The Western Canon', works_path %></p><i class="fa fa-angle-right"></i><p><%= @work.title %></p>
	  </div>
	  <div class="hero">
	    <div class="image">
	      <% if @work.featured_image %>
	        <%= image_tag @work.featured_image.image.url.to_s %>
	      <% end %>
	    </div>
	    <div class="fields">
		    <%= f.text_field :title, class: "full" %>
		    <%= f.label :is_title %>
		    <%= f.check_box :is_title, class: "checkbox"  %>
		    <br />

		    <%= f.number_field :min_year, placeholder: "min year" %>

		    <%= f.text_field :max_year, placeholder: "max year" %>

		    <%= f.label :circa %>
		    <%= f.check_box :circa, class: "checkbox"  %>
		    <br />
		    <%= f.text_field :place, placeholder: "place", id:"search-edit", class: "full" %>
		   </div>
  	</div>

	  <div class="content-row">
	    <div class="why">
	      <h4>Why is it canonical?</h4>
	      <%= f.text_area :why %>
	    </div>
	    <div class="tags">
	      <div class="tag-container">
        	<p>Creators</p>
  				<%= f.text_field :creator_list, value: @work.send("creator_list").to_s %>
	      </div>
	      <div class="tag-container">
          <p>Locations</p>
          <%= f.text_field :location_list, value: @work.send("location_list").to_s %>
	      </div>
	      <div class="tag-container">
	        <p>Languages</p>
          <%= f.text_field :language_list, value: @work.send("language_list").to_s %>
	      </div>
	      <div class="tag-container">
	        <p>Periods</p>
          <%= f.text_field :period_list, value: @work.send("period_list").to_s %>
	      </div>
	      <div class="tag-container">
	        <p>Media</p>
          <%= f.text_field :medium_list, value: @work.send("medium_list").to_s %>
	      </div>
	    </div>
	  </div>

	  <div class="media-row">
	    <h3>Images and Videos</h3>
	    <div class="new-object">
		    <div class="wrap">
		      <p>New media object? <%= link_to "Click here", new_media_object_path(:work_id => @work.id) %>.</p>
		    </div>
	   	</div>
	    <% @work.media_objects.each do |mo| %>
	      <div class="media-container">
	        <% if mo.image? %>
	          <a class="fancybox-image" href=<%= mo.image.url.to_s %>><%= image_tag mo.image.url.to_s %></a>
	        <% elsif mo.video? %>
	          <a class="fancybox-video" href=<%= "http://www.youtube.com/watch?v=#{mo.video}?fs=1&amp;autoplay=1" %>><%= image_tag "http://img.youtube.com/vi/#{mo.video}/0.jpg" %></a>
	        <% end %>   
	        <p><i><%= mo.caption %></i></p>
	        <%= link_to 'Edit media', edit_media_object_path(mo, :work_id => @work.id) %>
	      </div>
	    <% end %>
	  </div>
	  <div class="resources-row">
	    <h3>Resources</h3>
	    <div class="new-object">
		    <div class="wrap">
		      <p>New resource object? <%= link_to "Click here", new_resource_object_path(:work_id => @work.id) %>.</p>
		    </div>
	   	</div>
	    <% @work.resource_objects.each do |ro| %>
	      <div class="resource">
	        <div class="link-title">
	          <a href=<%= ro.link %> target="_blank"><%= ro.title %></a>
	        </div>
	        <div class="description">
	          <p><%= ro.description %></p>
	          <%= link_to 'Edit resource', edit_resource_object_path(ro, :work_id => @work.id) %>
	        </div>
	      </div>
	    <% end %>
	  </div>

	  <div class="push"></div>
	</div>
	<div class="new-work">
    <div class="wrap">
      <p>All done? <%= f.submit class: "button button-blue" %>
    <%= link_to 'Cancel', works_path %></p>
    </div>
  </div>	   

<% end %>

<script>
	var input2 = document.getElementById('search-edit');

	var autocomplete2 = new google.maps.places.Autocomplete(input2);
</script>

app/views/works/index.html.erb
<% if user_signed_in? %>
	<div class="new-work">
		<div class="wrap">
			<p>Got another work? <%= link_to 'Click here to add it', new_work_path %>.</p>
		</div>
	</div>
<% end %>

<div class="container filter">
	<div class="wrap">
		<div class="filter-inner">
			<%= form_for :artobject, url: { :action => "index" }, html: { method: :get } do |f| %>
			  <%= text_field_tag :tags, @tags ? @tags : nil, placeholder: "Separate search terms by comma" %>
			  <%= f.submit "Submit" %>
			  <%= link_to "Reset", works_path %>
			<% end %>
		</div>
	</div>
	<div id="filter-button">
		<p>Filter</p>
	</div>
</div>

<div class="container site-inner index">	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	<h1>The Western Canon</h1>

	<% @works.each do |work| %>
		<% if work.is_title %>
	  	<h2><i><%= link_to work.title, work %><i></h2>
	  <% else %>
	  	<h2><%= link_to work.title, work %></h2>
	  <% end %>
	<% end %>

	<br>

	
	<div class="push"></div>
</div>

app/views/works/new.html.erb
<div class="container site-inner new">	
	<h1>New Work</h1>

	<%= render 'form' %>

	<div class="push"></div>
</div>

<script>
	var input1 = document.getElementById('search-new');

	var autocomplete1 = new google.maps.places.Autocomplete(input1);
</script>

app/views/works/show.html.erb
<% if user_signed_in? %>
  <div class="new-work">
    <div class="wrap">
      <p>Want to change something? <%= link_to 'Click here to edit this work', edit_work_path(@work) %>.</p>
    </div>
  </div>
<% end %>

<div class="container site-inner show">  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="breadcrumb-container">
    <p><%= link_to 'The Western Canon', works_path %></p><i class="fa fa-angle-right"></i><p><%= @work.title %></p>
  </div>
  <div class="hero">
    <div class="image">
      <% if @work.featured_image %>
        <%= image_tag @work.featured_image.image.url.to_s %>
      <% end %>
    </div>
    <% if @work.is_title %>
      <h2><i><%= @work.title %></i></h2>
    <% else %>
      <h2><%= @work.title %></h2>
    <% end %>
    <h3><%= happy_date(@work.min_year,@work.max_year,@work.circa) %></h3>
  </div>

  <div class="content-row">
    <div class="why">
      <h4>Why is it canonical?</h4>
      <p><%= @work.why %></p>
    </div>
    <div class="tags">
      <div class="tag-container">
        <% if @work.creator_list.count > 0 %>
          <p>Creators</p>
          <% @work.creator_list.each do |t| %>
            <%= link_to t, works_path(params.merge(:tags =>  t)) %>
          <% end %>
        <% end %>
      </div>
      <div class="tag-container">
        
        <% if @work.location_list.count > 0 %>
          <p>Locations</p>
          <% @work.location_list.each do |t| %>
            <%= link_to t, works_path(params.merge(:tags =>  t)) %>
          <% end %>
        <% end %>
      </div>
      <div class="tag-container">
        <% if @work.language_list.count > 0 %>
          <p>Languages</p>
          <% @work.language_list.each do |t| %>
            <%= link_to t, works_path(params.merge(:tags =>  t)) %>
          <% end %>
        <% end %>
      </div>
      <div class="tag-container">
        <% if @work.period_list.count > 0 %>
          <p>Periods</p>
          <% @work.period_list.each do |t| %>
            <%= link_to t, works_path(params.merge(:tags =>  t)) %>
          <% end %>
        <% end %>
      </div>
      <div class="tag-container">
        <% if @work.medium_list.count > 0 %>
          <p>Media</p>
          <% @work.medium_list.each do |t| %>
            <%= link_to t, works_path(params.merge(:tags =>  t)) %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="media-row">
    <h3>Images and Videos</h3>
    <% @work.media_objects.each do |mo| %>
      <div class="media-container">
        <% if mo.image? %>
          <a class="fancybox-image" href=<%= mo.image.url.to_s %>><%= image_tag mo.image.url.to_s %></a>
        <% elsif mo.video? %>
          <a class="fancybox-video" href=<%= "http://www.youtube.com/watch?v=#{mo.video}?fs=1&amp;autoplay=1" %>><%= image_tag "http://img.youtube.com/vi/#{mo.video}/0.jpg" %></a>
        <% end %>   
        <p><i><%= mo.caption %></i></p>
      </div>
    <% end %>
  </div>

  <div class="resources-row">
    <h3>Resources</h3>
    <% @work.resource_objects.each do |ro| %>
      <div class="resource">
        <div class="link-title">
          <a href=<%= ro.link %> target="_blank"><%= ro.title %></a>
        </div>
        <div class="description">
          <p><%= ro.description %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="push"></div>
</div>